version: '3.7' # 修正時点で最新のversionを記載しています。1.xは動きませんのでご注意を。
services:
    db:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            # 初期データを投入するSQLが格納されているdir
            - ./db/mysql_init:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d/
            # 永続化するときにマウントするdir
            - ./db/mysql_data:/var/lib/mysql
            - ./share:/temp
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
